//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITecsup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public byte[] EstaActivo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }

        public double?IGV
        {
            get => IGV;set
            {
                IGV = PrecioVenta
                    *0.18;
            }
        }

        
    }
}
